version: "3"

services:
  database:
    container_name: postgres-local
    image: postgres:bullseye
    # volumes:
    #   - ./postgres-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  
  pg-admin:
    container_name: pg-admin
    depends_on:
      - database
    image: dpage/pgadmin4:8.4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    # volumes:
    #   - ./pg-admin:/var/lib/pgadmin
  
  redis:
    container_name: redis-local
    image: redis
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander
    container_name: redis-commander
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=redis-local


networks:
  card-tokenizer-local:
    
# volumes:
#   pg-db-local:
#     external: true
   